spring:
  # 데이터베이스 관련 설정
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

  # 쿼리문 보이게 하는 설정
  jpa:
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print